### PR TITLE
Update OODT Engine in WINGS

### PR DESCRIPTION
**Pull request by lewismc**
Hi Folks, specifically @varunratnakar 
We are considering using WINGS to improve user experience of creating and managing  workflows in OODT. Also, it would be really nice to log provenance information about our workflows so WINGS sounds excellent.
I pull the code earlier today and noticed that it was a bit outdated. This PR therefore attempts to update some documentation and dependencies such that WINGS is compatible with the most recent OODT 1.2.5.

### CODE REVIEW

**Comment by lewismc** [comment]
There are some stub Override's which were required to compile and package the artifacts. It is of course the idea that these stubs be implemented at some stage. I am just not exactly sure what they are meant to do yet. I will find out more as I learn more about what WINGS does.

**Comment by lewismc** [comment]
I am experiencing the following when attempting to click on the Manage Data dropdown tab.
Any ideas folks?
```
HTTP Status 500 – Internal Server Error

Type Exception Report

Message A MultiException has 2 exceptions. They are:

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: A MultiException has 2 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on edu.isi.wings.portal.resources.DataResource

	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:432)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

A MultiException has 2 exceptions.  They are:
1. java.lang.NullPointerException
2. java.lang.IllegalStateException: Unable to perform operation: post construct on edu.isi.wings.portal.resources.DataResource

	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:83)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Root Cause

java.lang.NullPointerException
	edu.isi.wings.portal.classes.config.Config.getProperties(Config.java:554)
	edu.isi.wings.portal.classes.config.Config.getProperties(Config.java:529)
	edu.isi.wings.portal.controllers.DataController.<init>(DataController.java:74)
	edu.isi.wings.portal.resources.DataResource.init(DataResource.java:31)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:564)
	org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
	org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
	org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:83)
	org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:777)
	org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:740)
	org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:710)
	org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getInstance(AbstractHk2InjectionManager.java:184)
	org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getInstance(ImmediateHk2InjectionManager.java:54)
	org.glassfish.jersey.internal.inject.Injections.getOrCreate(Injections.java:129)
	org.glassfish.jersey.server.model.MethodHandler$ClassBasedMethodHandler.getInstance(MethodHandler.java:284)
	org.glassfish.jersey.server.internal.routing.PushMethodHandlerRouter.apply(PushMethodHandlerRouter.java:75)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:110)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage._apply(RoutingStage.java:113)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:93)
	org.glassfish.jersey.server.internal.routing.RoutingStage.apply(RoutingStage.java:62)
	org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
	org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:269)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Note The full stack trace of the root cause is available in the server logs.

Apache Tomcat/9.0.7
```

**Comment by lewismc** [comment]
My portal.properties looks as follows
```
{
    storage = 
    {
        local = /Users/lmcgibbn/.wings/storage;
        tdb = /Users/lmcgibbn/.wings/storage/TDB;
    }

    server = http://localhost:8080;
    graphviz = /usr/bin/dot;
    ontology = 
    {
        data = http://www.wings-workflows.org/ontology/data.owl;
        component = http://www.wings-workflows.org/ontology/component.owl;
        workflow = http://www.wings-workflows.org/ontology/workflow.owl;
        execution = http://www.wings-workflows.org/ontology/execution.owl;
        resource = http://www.wings-workflows.org/ontology/resource.owl;
    }

    execution = 
    {
        engine = 
        {
            name = OODT;
            implementation = edu.isi.wings.execution.engine.api.impl.oodt.OODTExecutionEngine;
            type = BOTH;
            properties = 
            {
                extern_data_catalog = edu.isi.wings.catalog.data.api.impl.oodt.DataCreationFM;
                oodt = 
                {
                    fmurl = http://localhost:9000;
                    fmpolicy = wings;
                    wmurl = http://localhost:9001;
                    wmsurl = http://localhost:8080/wings-oodt-wmservices;
                    curatorurl = http://localhost:8080/cas-curator;
                    archivedir = /usr/local/coal-sds-deploy/data/archive;
                }
            }
        }

        engine = 
        {
            name = Distributed;
            implementation = edu.isi.wings.execution.engine.api.impl.distributed.DistributedExecutionEngine;
            type = BOTH;
        }
    }
}
```

**Comment by lewismc** [comment]
Folks, any comments here? We are working to upgrade Wings to work with OODT and I would like to work this issue out with the Wings Dev team. Thanks in advance.
Lewis

**Comment by varunratnakar** [comment]
Hi Lewis,

This is very exciting ! I'm sorry I took a while to get back on this. I'll take a look at the issue you're facing.

- Varun

**Pull request merged**
