### PR TITLE
Add feature: duplicate component

### LINKED ISSUE #31: It is difficult to add categories and abstract components in the root level
I have created a new domain. Whenever I add a new component type, I must close all the other ones I have created before, otherwise it will create a component under the last selected one. 
That is, if I select a component I can't deselect it without having to close its corresponding window.

I wonder if it would be possible to move components by clicking and dragging them in the hierarchy.

### PR DESCRIPTION
**Pull request by sirspock**
Close #31

### CODE REVIEW

**Comment by dgarijo** [comment]
How can this be done? Is it available in the wings intance in MINT?
Thanks a lot!

**Comment by sirspock** [comment]
The merge request has been tested on [dev environment(https://wings.mint.isi.edu/users/mint/MINT-production/components), and it seems fine.

**Comment by sirspock** [comment]
I updated the wings mint instance.
image

**Comment by dgarijo** [comment]
Fantastic, I wanted to have this for a long time

**Comment by varunratnakar** [comment]
Great work Maximiliano.

IMO, it would be better to add the "Duplicate" entry to the right click menu on a component, rather than on top.

**Comment by dgarijo** [comment]
I would leave where it is. You can create, duplicate or delete a component :)

**Comment by varunratnakar** [comment]
In standard UIs, you would put uncommonly used functionality on the right click. Like copy/paste in your file browser, which is what this is like.

**Comment by dgarijo** [comment]
yeah, but that way you don't know it exists unless you click. If we have a proliferation of new buttons, I agree it should be moved. But in my opinion now it doesn't hurt to be shown explicitly.
In any case, you are the main architect of the tool, so I will be happy to follow your lead here

**Comment by sirspock** [comment]
For me, I would leave the two buttons and after we can test if a user can duplicate without the button in the toolbar.

**Comment by varunratnakar** [comment]
Ok, lets leave it as is then :)


On 7 May 2019, at 00:26, Maximiliano Osorio <notifications@github.com<mailto:notifications@github.com>> wrote:


For me, I would leave the two buttons and after we can test if a user can duplicate without the button in the toolbar.

**Pull request merged**
